<%@ page contentType="text/html; charset=gb2312" %>                       
 
           <tr>
            <table width="778" border="0"  cellpadding="0" align="center" bgcolor="#E4EDFB">
             <tr> 
                <td width="39.9"></td><td bgcolor="#000000" width="700.2"><img src="images/Spacer.gif" width="1" height="1"></td><td width="39.9"></td>
            </tr>
            <tr>
               <td hight="5">&nbsp;</td>
            </tr>
              <tr> 
              <td></td>
                <td> 
                  <p align="center">
网上书店管理系统
<!--TTelephone-->
电话:
010-86868686
<!--TEMail-->
 电子邮件:

<A HREF='mailto:longlyboyhe@126.com
<!--Email-->

'>
longlyboyhe@126.com</A><br>
 版权所有
@2013 JavaWeb项目开发入门<br>
<a>本站请使用IE6.0或以上版本 1024*768为最佳显示效果</a>
</p>
                </td><td></td>
              </tr>
              </table>                
           
  </tr>
  
</table>
<table width="778" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td><img src="images/index_bottom.gif" width="778" height="80"></td>
  </tr>
</table>
</BODY>
</HTML>
