<%@ page contentType="text/html; charset=gb2312"%>
<table width="100%" border="0" cellspacing="1" cellpadding="1">
	<tr>
		<td width="20">
			&nbsp;
		</td>
		<td>
			<a href="orderinfo.jsp">查看订单情况</a>
		</td>
	</tr>
	<tr>
		<td width="20">
			&nbsp;
		</td>
		<td>
			<a href="modify.jsp">修改个人信息</a>
		</td>
	</tr>
	<tr>
		<td width="20">
			&nbsp;
		</td>
		<td>
			<a href="shopcar.jsp">查看我的购物车</a>
		</td>
	</tr>
</table>
